# Generated by Django 4.0 on 2021-12-22 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название департамента')),
            ],
            options={
                'verbose_name': 'департамент',
                'verbose_name_plural': 'департаменты',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(default='default.jpg', upload_to='', verbose_name='логотип')),
                ('position', models.CharField(max_length=200, verbose_name='должность')),
                ('salary', models.IntegerField(verbose_name='зарплата')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='staff.department', verbose_name='департамент')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
    ]
